// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export namespace main {
  
  export class QrcodeResult {
    key: string;
    image: string;
    
    static createFrom(source: any = {}) {
      return new QrcodeResult(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) {
        source = JSON.parse(source);
      }

      this.key = source['key'];
      this.image = source['image'];
      
    }
  }
  
  export class QrcodeStatus {
    code: number;
    message: string;
    
    static createFrom(source: any = {}) {
      return new QrcodeStatus(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) {
        source = JSON.parse(source);
      }

      this.code = source['code'];
      this.message = source['message'];
      
    }
  }
  
  export class UserProfile {
    userID: number;
    nickname: string;
    avatarURL: string;
    vipType: number;
    status: number;
    
    static createFrom(source: any = {}) {
      return new UserProfile(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) {
        source = JSON.parse(source);
      }

      this.userID = source['userID'];
      this.nickname = source['nickname'];
      this.avatarURL = source['avatarURL'];
      this.vipType = source['vipType'];
      this.status = source['status'];
      
    }
  }
  
}
